<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MpWallet.Money\MpWallet.Money.csproj" />
    <ProjectReference Include="..\MpWallet.Storage\MpWallet.Storage.csproj" />
  </ItemGroup>

</Project>
