// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MpWallet.Wallets.Storage.SQLite;

#nullable disable

namespace MpWallet.Wallets.Storage.SQLite.Migrations.Instances
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MpWallet.Wallets.Storage.SQLite.Entities.WalletConfigurationAdditionalPropertyEntity", b =>
                {
                    b.Property<string>("WalletId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("wallet_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("WalletId", "Key")
                        .HasName("wallet_additional_properties_primary_key");

                    b.ToTable("wallet_configuration_additional_properties", (string)null);
                });

            modelBuilder.Entity("MpWallet.Wallets.Storage.SQLite.Entities.WalletConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_wallet_primary_key");

                    b.ToTable("wallet_configurations", (string)null);
                });

            modelBuilder.Entity("MpWallet.Wallets.Storage.SQLite.Entities.WalletConfigurationAdditionalPropertyEntity", b =>
                {
                    b.HasOne("MpWallet.Wallets.Storage.SQLite.Entities.WalletConfigurationEntity", "Wallet")
                        .WithMany("AdditionalProperties")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MpWallet.Wallets.Storage.SQLite.Entities.WalletConfigurationEntity", b =>
                {
                    b.Navigation("AdditionalProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
