<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MpWallet.CBR.Client\MpWallet.CBR.Client.csproj" />
    <ProjectReference Include="..\MpWallet.ExchangeRates.Abstractions\MpWallet.ExchangeRates.Abstractions.csproj" />
    <ProjectReference Include="..\MpWallet.Time\MpWallet.Time.csproj" />
  </ItemGroup>

</Project>
